import type { Profile, Buyer, BuyerContact, Factory, Supplier } from "@/types";
import { isoDate } from "./rng";

export const profiles: Profile[] = [
  { id: "user-admin", fullName: "Karthik Ramaswamy", email: "admin@texcroft.demo", role: "admin" },
  { id: "user-mgmt", fullName: "Priya Natarajan", email: "management@texcroft.demo", role: "management" },
  { id: "user-mrc-1", fullName: "Kranti Sharma", email: "kranti@texcroft.demo", role: "merchandiser" },
  { id: "user-mrc-2", fullName: "Arjun Vellore", email: "arjun@texcroft.demo", role: "merchandiser" },
  { id: "user-src", fullName: "Divya Chandran", email: "sourcing@texcroft.demo", role: "sourcing_manager" },
  { id: "user-prod", fullName: "Manoj Pillai", email: "production@texcroft.demo", role: "production_manager" },
  { id: "user-qc", fullName: "Lakshmi Iyer", email: "qc@texcroft.demo", role: "qc_inspector" },
  { id: "user-fin", fullName: "Suresh Bala", email: "finance@texcroft.demo", role: "finance" },
  {
    id: "user-factory",
    fullName: "Ravi Kumar",
    email: "factory@texcroft.demo",
    role: "factory_partner",
    factoryId: "factory-02",
  },
  {
    id: "user-buyer",
    fullName: "James Whitfield",
    email: "buyer@texcroft.demo",
    role: "buyer",
    buyerId: "buyer-01",
  },
];

export const buyers: Buyer[] = [
  {
    id: "buyer-01",
    companyName: "North & Row Apparel",
    contactName: "James Whitfield",
    email: "james@northandrow.co.uk",
    phone: "+44 20 7946 0958",
    country: "United Kingdom",
    currency: "GBP",
    shippingLocation: "Felixstowe, UK",
    paymentTerms: "30% advance, 70% against BL",
    taxDetails: "GB-VAT-774213",
    createdAt: isoDate(2024, 3, 12),
    updatedAt: isoDate(2026, 9, 10),
  },
  {
    id: "buyer-02",
    companyName: "Harrington Clothing Co.",
    contactName: "Megan Harrington",
    email: "megan@harringtonclothing.com",
    phone: "+1 212 555 0143",
    country: "United States",
    currency: "USD",
    shippingLocation: "Newark, NJ, USA",
    paymentTerms: "L/C at sight",
    taxDetails: "US-EIN-45-2210981",
    createdAt: isoDate(2023, 11, 4),
    updatedAt: isoDate(2026, 9, 8),
  },
  {
    id: "buyer-03",
    companyName: "Urban Thread GmbH",
    contactName: "Lukas Bergmann",
    email: "lukas@urbanthread.de",
    phone: "+49 30 5557 2210",
    country: "Germany",
    currency: "EUR",
    shippingLocation: "Hamburg, Germany",
    paymentTerms: "50% advance, 50% before dispatch",
    taxDetails: "DE-VAT-284471125",
    createdAt: isoDate(2024, 1, 20),
    updatedAt: isoDate(2026, 9, 5),
  },
  {
    id: "buyer-04",
    companyName: "Solstice Apparel",
    contactName: "Rachel Kim",
    email: "rachel@solsticeapparel.com",
    phone: "+1 310 555 0199",
    country: "United States",
    currency: "USD",
    shippingLocation: "Long Beach, CA, USA",
    paymentTerms: "30% advance, 70% against BL",
    taxDetails: "US-EIN-88-1123456",
    createdAt: isoDate(2024, 6, 2),
    updatedAt: isoDate(2026, 8, 30),
  },
  {
    id: "buyer-05",
    companyName: "Maison North",
    contactName: "Camille Dubois",
    email: "camille@maisonnorth.fr",
    phone: "+33 1 4550 6621",
    country: "France",
    currency: "EUR",
    shippingLocation: "Le Havre, France",
    paymentTerms: "L/C 60 days",
    taxDetails: "FR-VAT-77552211",
    createdAt: isoDate(2023, 9, 18),
    updatedAt: isoDate(2026, 9, 1),
  },
  {
    id: "buyer-06",
    companyName: "Atlas Retail Group",
    contactName: "Daniel Ferreira",
    email: "daniel@atlasretail.com",
    phone: "+1 646 555 0110",
    country: "United States",
    currency: "USD",
    shippingLocation: "Savannah, GA, USA",
    paymentTerms: "30% advance, 70% against BL",
    taxDetails: "US-EIN-12-9988776",
    createdAt: isoDate(2025, 1, 10),
    updatedAt: isoDate(2026, 8, 22),
  },
  {
    id: "buyer-07",
    companyName: "Nordform Clothing",
    contactName: "Elin Karlsson",
    email: "elin@nordform.se",
    phone: "+46 8 555 2231",
    country: "Sweden",
    currency: "EUR",
    shippingLocation: "Gothenburg, Sweden",
    paymentTerms: "50% advance, 50% before dispatch",
    taxDetails: "SE-VAT-556677889",
    createdAt: isoDate(2024, 10, 5),
    updatedAt: isoDate(2026, 9, 3),
  },
  {
    id: "buyer-08",
    companyName: "Kestrel & Co.",
    contactName: "Oliver Hughes",
    email: "oliver@kestrelco.co.uk",
    phone: "+44 161 555 0132",
    country: "United Kingdom",
    currency: "GBP",
    shippingLocation: "Southampton, UK",
    paymentTerms: "30% advance, 70% against BL",
    taxDetails: "GB-VAT-661223",
    createdAt: isoDate(2025, 2, 14),
    updatedAt: isoDate(2026, 8, 18),
  },
  {
    id: "buyer-09",
    companyName: "Meridian Basics",
    contactName: "Sophia Alden",
    email: "sophia@meridianbasics.com",
    phone: "+1 415 555 0176",
    country: "United States",
    currency: "USD",
    shippingLocation: "Oakland, CA, USA",
    paymentTerms: "L/C at sight",
    taxDetails: "US-EIN-33-4455667",
    createdAt: isoDate(2024, 4, 28),
    updatedAt: isoDate(2026, 9, 6),
  },
  {
    id: "buyer-10",
    companyName: "Vantage Sportswear",
    contactName: "Michael O'Brien",
    email: "michael@vantagesportswear.com",
    phone: "+353 1 555 8821",
    country: "Ireland",
    currency: "EUR",
    shippingLocation: "Dublin Port, Ireland",
    paymentTerms: "30% advance, 70% against BL",
    taxDetails: "IE-VAT-3311224S",
    createdAt: isoDate(2024, 8, 15),
    updatedAt: isoDate(2026, 8, 28),
  },
  {
    id: "buyer-11",
    companyName: "Fieldstone Trading",
    contactName: "Grace Thompson",
    email: "grace@fieldstonetrading.com",
    phone: "+1 214 555 0161",
    country: "United States",
    currency: "USD",
    shippingLocation: "Houston, TX, USA",
    paymentTerms: "30% advance, 70% against BL",
    taxDetails: "US-EIN-77-2233445",
    createdAt: isoDate(2025, 5, 9),
    updatedAt: isoDate(2026, 8, 12),
  },
  {
    id: "buyer-12",
    companyName: "Highline Denim Co.",
    contactName: "Thomas Reid",
    email: "thomas@highlinedenim.com",
    phone: "+1 646 555 0198",
    country: "United States",
    currency: "USD",
    shippingLocation: "Los Angeles, CA, USA",
    paymentTerms: "L/C 60 days",
    taxDetails: "US-EIN-55-6677889",
    createdAt: isoDate(2025, 7, 21),
    updatedAt: isoDate(2026, 9, 2),
  },
];

export const buyerContacts: BuyerContact[] = buyers.map((b, i) => ({
  id: `contact-${i + 1}`,
  buyerId: b.id,
  name: b.contactName,
  roleTitle: "Head of Buying",
  email: b.email,
  phone: b.phone,
  isPrimary: true,
}));

export const factories: Factory[] = [
  {
    id: "factory-01",
    name: "Texcroft Unit 01",
    location: "Tiruppur, Tamil Nadu",
    contactName: "Senthil Kumar",
    contactPhone: "+91 98430 11234",
    capabilities: ["knits", "printing", "finishing"],
    dailyCapacityPieces: 12000,
  },
  {
    id: "factory-02",
    name: "Texcroft Unit 02",
    location: "Tiruppur, Tamil Nadu",
    contactName: "Ravi Kumar",
    contactPhone: "+91 98430 55678",
    capabilities: ["knits", "embroidery", "washing", "finishing"],
    dailyCapacityPieces: 9000,
  },
  {
    id: "factory-03",
    name: "KnitWorks Tiruppur",
    location: "Tiruppur, Tamil Nadu",
    contactName: "Muthu Selvam",
    contactPhone: "+91 94430 22110",
    capabilities: ["knits", "wovens"],
    dailyCapacityPieces: 7000,
  },
  {
    id: "factory-04",
    name: "Southern Stitching Unit",
    location: "Coimbatore, Tamil Nadu",
    contactName: "Bala Subramaniam",
    contactPhone: "+91 90420 88221",
    capabilities: ["wovens", "printing", "washing"],
    dailyCapacityPieces: 6000,
  },
  {
    id: "factory-05",
    name: "Avinashi Apparel Works",
    location: "Avinashi, Tamil Nadu",
    contactName: "Ganesh Moorthy",
    contactPhone: "+91 96290 44112",
    capabilities: ["knits", "embroidery"],
    dailyCapacityPieces: 5000,
  },
];

export const suppliers: Supplier[] = [
  {
    id: "supplier-01",
    name: "Sri Lakshmi Knits",
    location: "Tiruppur, Tamil Nadu",
    contactName: "Murugan S.",
    contactEmail: "murugan@srilakshmiknits.in",
    contactPhone: "+91 94420 11223",
    materialCategories: ["fabric", "rib"],
    leadTimeDays: 12,
    paymentTerms: "30 days credit",
  },
  {
    id: "supplier-02",
    name: "Kaveri Fabrics",
    location: "Erode, Tamil Nadu",
    contactName: "Anitha R.",
    contactEmail: "anitha@kaverifabrics.in",
    contactPhone: "+91 90470 33221",
    materialCategories: ["fabric"],
    leadTimeDays: 15,
    paymentTerms: "Advance 50%",
  },
  {
    id: "supplier-03",
    name: "Prime Labels",
    location: "Tiruppur, Tamil Nadu",
    contactName: "Suresh N.",
    contactEmail: "suresh@primelabels.in",
    contactPhone: "+91 98940 55112",
    materialCategories: ["labels"],
    leadTimeDays: 7,
    paymentTerms: "15 days credit",
  },
  {
    id: "supplier-04",
    name: "Southern Trims",
    location: "Tiruppur, Tamil Nadu",
    contactName: "Vijay Anand",
    contactEmail: "vijay@southerntrims.in",
    contactPhone: "+91 89250 77441",
    materialCategories: ["buttons", "zippers", "thread"],
    leadTimeDays: 10,
    paymentTerms: "30 days credit",
  },
  {
    id: "supplier-05",
    name: "Tiruppur Packaging Co.",
    location: "Tiruppur, Tamil Nadu",
    contactName: "Ramesh Babu",
    contactEmail: "ramesh@tiruppurpackaging.in",
    contactPhone: "+91 93450 22887",
    materialCategories: ["packaging"],
    leadTimeDays: 6,
    paymentTerms: "15 days credit",
  },
  {
    id: "supplier-06",
    name: "Coimbatore Cotton Mills",
    location: "Coimbatore, Tamil Nadu",
    contactName: "Elango P.",
    contactEmail: "elango@cbecottonmills.in",
    contactPhone: "+91 96550 12980",
    materialCategories: ["fabric"],
    leadTimeDays: 18,
    paymentTerms: "Advance 40%",
  },
  {
    id: "supplier-07",
    name: "Nallar Zippers & Trims",
    location: "Chennai, Tamil Nadu",
    contactName: "Karthik D.",
    contactEmail: "karthik@nallartrims.in",
    contactPhone: "+91 94440 66512",
    materialCategories: ["zippers", "buttons"],
    leadTimeDays: 9,
    paymentTerms: "30 days credit",
  },
  {
    id: "supplier-08",
    name: "VelTex Dyes & Processing",
    location: "Tiruppur, Tamil Nadu",
    contactName: "Meena V.",
    contactEmail: "meena@veltexdyes.in",
    contactPhone: "+91 97880 33660",
    materialCategories: ["fabric", "other"],
    leadTimeDays: 8,
    paymentTerms: "15 days credit",
  },
];
