import type { Style, StyleVersion } from "@/types";
import { isoDate } from "./rng";

const SIZES_ADULT = ["XS", "S", "M", "L", "XL", "XXL"];
const SIZES_KIDS = ["2-3Y", "4-5Y", "6-7Y", "8-9Y", "10-11Y"];

export const styles: Style[] = [
  {
    id: "style-01",
    styleCode: "TC-HD-041",
    name: "Heavyweight Oversized Hoodie",
    category: "Hoodie",
    buyerId: "buyer-01",
    fabric: "100% Cotton French Terry",
    composition: "100% Cotton",
    gsm: 240,
    colours: ["Black", "Charcoal", "Cream"],
    sizes: SIZES_ADULT,
    measurements: [
      { point: "Chest Width", values: { XS: 58, S: 60, M: 62, L: 64, XL: 66, XXL: 68 } },
      { point: "Body Length", values: { XS: 68, S: 70, M: 72, L: 74, XL: 76, XXL: 78 } },
    ],
    printDetails: "Chest embroidery logo",
    washType: "Garment dyed, enzyme wash",
    labelInstructions: "Woven main label, printed care label",
    packagingInstructions: "Individual poly bag, 1 dozen per carton",
    currentVersion: 2,
    approvalStatus: "approved",
    createdBy: "user-mrc-1",
    createdAt: isoDate(2026, 6, 2),
    updatedAt: isoDate(2026, 8, 15),
  },
  {
    id: "style-02",
    styleCode: "TC-PL-018",
    name: "Pique Polo",
    category: "Polo",
    buyerId: "buyer-02",
    fabric: "100% Cotton Pique",
    composition: "100% Cotton",
    gsm: 220,
    colours: ["Navy", "White", "Forest Green"],
    sizes: SIZES_ADULT,
    measurements: [{ point: "Chest Width", values: { XS: 50, S: 52, M: 54, L: 56, XL: 58, XXL: 60 } }],
    labelInstructions: "Woven neck label",
    packagingInstructions: "Flat pack, 1 dozen per carton",
    currentVersion: 1,
    approvalStatus: "approved",
    createdBy: "user-mrc-2",
    createdAt: isoDate(2026, 5, 20),
    updatedAt: isoDate(2026, 7, 10),
  },
  {
    id: "style-03",
    styleCode: "TC-JG-027",
    name: "French Terry Jogger",
    category: "Bottoms",
    buyerId: "buyer-03",
    fabric: "80% Cotton 20% Polyester French Terry",
    composition: "80% Cotton, 20% Polyester",
    gsm: 280,
    colours: ["Heather Grey", "Black"],
    sizes: SIZES_ADULT,
    measurements: [{ point: "Waist", values: { XS: 66, S: 70, M: 74, L: 78, XL: 82, XXL: 86 } }],
    washType: "Silicone wash",
    packagingInstructions: "Individual poly bag",
    currentVersion: 1,
    approvalStatus: "approved",
    createdBy: "user-mrc-1",
    createdAt: isoDate(2026, 4, 11),
    updatedAt: isoDate(2026, 6, 2),
  },
  {
    id: "style-04",
    styleCode: "TC-TS-005",
    name: "Heavyweight Tee",
    category: "T-Shirt",
    buyerId: "buyer-04",
    fabric: "100% Cotton Jersey",
    composition: "100% Cotton",
    gsm: 220,
    colours: ["White", "Black", "Sand"],
    sizes: SIZES_ADULT,
    measurements: [{ point: "Chest Width", values: { XS: 48, S: 50, M: 52, L: 54, XL: 56, XXL: 58 } }],
    packagingInstructions: "Flat pack",
    currentVersion: 3,
    approvalStatus: "approved",
    createdBy: "user-mrc-2",
    createdAt: isoDate(2025, 12, 3),
    updatedAt: isoDate(2026, 8, 1),
  },
  {
    id: "style-05",
    styleCode: "TC-KT-011",
    name: "Kids Jersey Tee",
    category: "T-Shirt",
    buyerId: "buyer-05",
    fabric: "100% Cotton Single Jersey",
    composition: "100% Cotton",
    gsm: 160,
    colours: ["Sky Blue", "Yellow", "White"],
    sizes: SIZES_KIDS,
    measurements: [],
    packagingInstructions: "Individual poly bag with size sticker",
    currentVersion: 1,
    approvalStatus: "approved",
    createdBy: "user-mrc-1",
    createdAt: isoDate(2026, 3, 18),
    updatedAt: isoDate(2026, 5, 5),
  },
  {
    id: "style-06",
    styleCode: "TC-PF-022",
    name: "Performance Tee",
    category: "T-Shirt",
    buyerId: "buyer-10",
    fabric: "100% Recycled Polyester Interlock",
    composition: "100% Recycled Polyester",
    gsm: 150,
    colours: ["Black", "Charcoal", "Royal Blue"],
    sizes: SIZES_ADULT,
    measurements: [],
    printDetails: "Reflective heat transfer logo",
    currentVersion: 2,
    approvalStatus: "approved",
    createdBy: "user-mrc-2",
    createdAt: isoDate(2026, 2, 9),
    updatedAt: isoDate(2026, 7, 22),
  },
  {
    id: "style-07",
    styleCode: "TC-PJ-014",
    name: "Cotton Pyjama Set",
    category: "Loungewear",
    buyerId: "buyer-09",
    fabric: "100% Cotton Flannel",
    composition: "100% Cotton",
    gsm: 180,
    colours: ["Grey Stripe", "Navy Stripe"],
    sizes: SIZES_ADULT,
    measurements: [],
    packagingInstructions: "Folded, 1 set per poly bag",
    currentVersion: 1,
    approvalStatus: "approved",
    createdBy: "user-mrc-1",
    createdAt: isoDate(2026, 1, 25),
    updatedAt: isoDate(2026, 4, 14),
  },
  {
    id: "style-08",
    styleCode: "TC-ZH-033",
    name: "Zip Hoodie",
    category: "Hoodie",
    buyerId: "buyer-06",
    fabric: "80% Cotton 20% Polyester Fleece",
    composition: "80% Cotton, 20% Polyester",
    gsm: 300,
    colours: ["Black", "Grey Melange"],
    sizes: SIZES_ADULT,
    measurements: [],
    labelInstructions: "Woven main label",
    currentVersion: 2,
    approvalStatus: "approved",
    createdBy: "user-mrc-2",
    createdAt: isoDate(2025, 11, 15),
    updatedAt: isoDate(2026, 6, 20),
  },
  {
    id: "style-09",
    styleCode: "TC-CN-009",
    name: "Crewneck Sweatshirt",
    category: "Sweatshirt",
    buyerId: "buyer-07",
    fabric: "100% Cotton Loopback Terry",
    composition: "100% Cotton",
    gsm: 320,
    colours: ["Oatmeal", "Navy", "Black"],
    sizes: SIZES_ADULT,
    measurements: [],
    currentVersion: 1,
    approvalStatus: "approved",
    createdBy: "user-mrc-1",
    createdAt: isoDate(2026, 5, 3),
    updatedAt: isoDate(2026, 7, 28),
  },
  {
    id: "style-10",
    styleCode: "TC-PL-019",
    name: "Pique Polo",
    category: "Polo",
    buyerId: "buyer-08",
    fabric: "100% Cotton Pique",
    composition: "100% Cotton",
    gsm: 210,
    colours: ["Bottle Green", "Maroon"],
    sizes: SIZES_ADULT,
    measurements: [],
    currentVersion: 1,
    approvalStatus: "pending_approval",
    createdBy: "user-mrc-2",
    createdAt: isoDate(2026, 7, 1),
    updatedAt: isoDate(2026, 8, 20),
  },
  {
    id: "style-11",
    styleCode: "TC-TS-006",
    name: "Heavyweight Tee",
    category: "T-Shirt",
    buyerId: "buyer-11",
    fabric: "100% Cotton Jersey",
    composition: "100% Cotton",
    gsm: 200,
    colours: ["White", "Natural"],
    sizes: SIZES_ADULT,
    measurements: [],
    currentVersion: 1,
    approvalStatus: "approved",
    createdBy: "user-mrc-1",
    createdAt: isoDate(2026, 4, 22),
    updatedAt: isoDate(2026, 6, 11),
  },
  {
    id: "style-12",
    styleCode: "TC-HD-042",
    name: "Oversized Hoodie",
    category: "Hoodie",
    buyerId: "buyer-12",
    fabric: "100% Cotton Fleece",
    composition: "100% Cotton",
    gsm: 260,
    colours: ["Washed Black", "Stone"],
    sizes: SIZES_ADULT,
    measurements: [],
    washType: "Stone wash",
    currentVersion: 1,
    approvalStatus: "draft",
    createdBy: "user-mrc-2",
    createdAt: isoDate(2026, 8, 5),
    updatedAt: isoDate(2026, 9, 1),
  },
];

// Round out to 25 styles with lighter-weight generated variants for catalogue depth.
const EXTRA_NAMES: { name: string; category: string; fabric: string; gsm: number }[] = [
  { name: "French Terry Jogger", category: "Bottoms", fabric: "French Terry", gsm: 270 },
  { name: "Performance Tee", category: "T-Shirt", fabric: "Polyester Interlock", gsm: 150 },
  { name: "Kids Jersey Tee", category: "T-Shirt", fabric: "Cotton Single Jersey", gsm: 160 },
  { name: "Crewneck Sweatshirt", category: "Sweatshirt", fabric: "Loopback Terry", gsm: 300 },
  { name: "Zip Hoodie", category: "Hoodie", fabric: "Cotton Fleece", gsm: 290 },
  { name: "Cotton Pyjama Set", category: "Loungewear", fabric: "Cotton Flannel", gsm: 170 },
  { name: "Pique Polo", category: "Polo", fabric: "Cotton Pique", gsm: 215 },
  { name: "Heavyweight Tee", category: "T-Shirt", fabric: "Cotton Jersey", gsm: 210 },
  { name: "Oversized Hoodie", category: "Hoodie", fabric: "Cotton French Terry", gsm: 250 },
  { name: "French Terry Jogger", category: "Bottoms", fabric: "Cotton French Terry", gsm: 260 },
  { name: "Performance Tee", category: "T-Shirt", fabric: "Recycled Polyester", gsm: 145 },
  { name: "Crewneck Sweatshirt", category: "Sweatshirt", fabric: "Cotton Terry", gsm: 310 },
  { name: "Kids Jersey Tee", category: "T-Shirt", fabric: "Cotton Single Jersey", gsm: 155 },
];

const buyerCycle = ["buyer-01", "buyer-02", "buyer-03", "buyer-04", "buyer-05", "buyer-06", "buyer-07", "buyer-08", "buyer-09", "buyer-10", "buyer-11", "buyer-12"];

EXTRA_NAMES.forEach((extra, i) => {
  const n = i + 13;
  const isKids = extra.name.includes("Kids");
  styles.push({
    id: `style-${String(n).padStart(2, "0")}`,
    styleCode: `TC-${extra.category.slice(0, 2).toUpperCase()}-${(100 + n).toString()}`,
    name: extra.name,
    category: extra.category,
    buyerId: buyerCycle[n % buyerCycle.length],
    fabric: `${extra.fabric}`,
    composition: extra.fabric.includes("Recycled") ? "100% Recycled Polyester" : "100% Cotton",
    gsm: extra.gsm,
    colours: ["Black", "Navy", "Grey Melange"],
    sizes: isKids ? SIZES_KIDS : SIZES_ADULT,
    measurements: [],
    currentVersion: 1,
    approvalStatus: i % 4 === 0 ? "pending_approval" : "approved",
    createdBy: i % 2 === 0 ? "user-mrc-1" : "user-mrc-2",
    createdAt: isoDate(2026, (i % 6) + 1, 10),
    updatedAt: isoDate(2026, (i % 6) + 3, 15),
  });
});

export const styleVersions: StyleVersion[] = styles
  .filter((s) => s.currentVersion > 1)
  .flatMap((s) =>
    Array.from({ length: s.currentVersion }, (_, i) => ({
      id: `styleversion-${s.id}-${i + 1}`,
      styleId: s.id,
      versionNumber: i + 1,
      changeSummary:
        i + 1 === s.currentVersion
          ? "Updated GSM and colour palette per buyer feedback"
          : "Initial tech pack submission",
      createdBy: s.createdBy,
      createdAt: s.createdAt,
    }))
  );
